version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile.server
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    command: gunicorn --bind 0.0.0.0:8000 core.wsgi:application

  frontend:
    build:
      context: .
      dockerfile: dockerfile.client
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    command: npm start
