# Generated by Django 5.1.5 on 2025-01-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ballet", "발레"),
                            ("modern", "현대무용"),
                            ("korea", "한국무용"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("basic", "입문반"), ("performance", "작품반")],
                        max_length=12,
                    ),
                ),
                ("times", models.JSONField()),
                (
                    "pass_type",
                    models.CharField(
                        choices=[
                            ("1", "1회 체험권"),
                            ("2", "주 1회권"),
                            ("3", "주 2회권"),
                            ("4", "주 3회권"),
                        ],
                        max_length=1,
                    ),
                ),
                ("route", models.IntegerField()),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("contact", models.CharField(max_length=100)),
            ],
        ),
    ]
