# Generated by Django 5.1.5 on 2025-01-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timemanageapp", "0002_alter_course_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="enrollment_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
