# Generated by Django 5.1.5 on 2025-01-18 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timemanageapp", "0003_course_enrollment_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pass_type",
                    models.CharField(
                        choices=[
                            ("1", "1회 체험권"),
                            ("2", "주 1회권"),
                            ("3", "주 2회권"),
                            ("4", "주 3회권"),
                        ],
                        max_length=1,
                    ),
                ),
                ("enrollment_date", models.DateTimeField(auto_now_add=True)),
                ("contact", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timemanageapp.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "course")},
            },
        ),
    ]
