# Generated by Django 5.1.5 on 2025-01-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timemanageapp", "0004_courseenrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseenrollment",
            name="payed",
            field=models.BooleanField(default=False),
        ),
    ]
