# Generated by Django 5.1.5 on 2025-01-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timemanageapp", "0005_courseenrollment_payed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="course",
            name="location",
        ),
        migrations.RemoveField(
            model_name="course",
            name="pass_type",
        ),
        migrations.RemoveField(
            model_name="course",
            name="route",
        ),
        migrations.AddField(
            model_name="courseenrollment",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="courseenrollment",
            name="route",
            field=models.IntegerField(default="1"),
        ),
    ]
